# Generated by Django 3.0.8 on 2020-08-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreputation',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewreputation',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewreputation',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
