# Generated by Django 3.1 on 2020-08-21 08:35

from django.db import migrations, models
import user.validation


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200820_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(max_length=50, validators=[user.validation.validate_birthday]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[user.validation.validate_email]),
        ),
    ]
